INSERT INTO CAR_PART_CATEGORY(NAME) VALUES('CAR_PART');
INSERT INTO CAR_PART_CATEGORY(NAME) VALUES('OIL');
INSERT INTO CAR_PART_CATEGORY(NAME) VALUES('ACCESSORIES');
INSERT INTO CAR_PART_CATEGORY(NAME) VALUES('OTHER');

INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('WINTER TYRE', 1, 250, '235/45/R18');
INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('MOTOR OIL', 2, 20, '10W 40');
INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('Tire chains for winter conditions', 3, 40, '235/45/R18');
INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('Tire chains for winter conditions', 3, 40, '235/45/R18');
INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('Carglass clean fluid', 4, 16, 'Winter mix');
INSERT INTO CAR_PART(NAME, CATEGORY_ID, PRICE, DESCRIPTION)
VALUES('Thule box', 3, 541, 'Roof box');

INSERT INTO USERS(username, password)
VALUES('admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW');

INSERT INTO USERS(username, password)
VALUES('user', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW');

INSERT INTO ROLE(name) VALUES ('ROLE_USER');
INSERT INTO ROLE(name) VALUES ('ROLE_ADMIN');

INSERT INTO USER_ROLE(user_id, role_id) VALUES(1, 1);
INSERT INTO USER_ROLE(user_id, role_id) VALUES(1, 2);
INSERT INTO USER_ROLE(user_id, role_id) VALUES(2, 1);