CREATE TABLE CAR_PART_CATEGORY(
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CAR_PART(
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRICE DECIMAL(6, 2) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CAR_PART_CATEGORY(ID)
);